# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup npm auth
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLIC_NPM_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build and Deploy Storybook
        run: yarn deploy-storybook --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish to GitHub Packages
        if: "startsWith(github.ref, 'refs/tags/v')" # Only run on version tags
        run: |
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
